### ISSUE TITLE
Working with Flexi auth

### ISSUE THREAD

**Issue by smoizs** [XMadMax/Codeigniter-3.0-with-XHMVC#1]
Hi, 

The previous version of this repo had flexi auth as part of the package. I see that there is no use of bundling it, but would anyone be aware of how to get Flexi auth's email's to work with this build?

I'm particularly stuck on getting it to work with XHMVC as flexi auth's model cant find where the email template view's are.

any help would be great.

P.S I'm using a fork of flexi auth (https://github.com/dansanti/flexi-auth) which is more compatible with CI 3 and fixes some of the original issues, with a bit of added functionality.

**Comment by XXPerez** [comment]
Hello,

Previous flexi-auth can work fine with current XHMVC, current original flexi-auth version have some problems. The fork you mentioned from dansanti seems to be working quite well. Now, I have all views working OK, but some problems on login. Give me more time to have it working. I will push flexi-auth within next days.

Thanks for your comments.

**Comment by smoizs** [comment]
@XMadMax so far the library works great with me but i'm particularly stuck with the sending of emails. I can't seem to figure out where to map the email templates too.

**Comment by XXPerez** [comment]
@smoizs, you refer to the function to obtain the template ? ..

From Flexi_auth_model.php:

public function send_email($email_to = NULL, $email_title = NULL, $data = NULL, $template = NULL)
.
.
.
        // Overwrite default template file to send email via template_data() function (Must be called prior to parent function).
        if (!empty($this->auth->template_data['template']))
        {
            $template = $this->auth->template_data['template'];
        }

```
    $message = $this->load->view($template, $data, TRUE);
```

.
.
.

**Comment by smoizs** [comment]
@XMadMax you are correct. This is the function that sends out the email. When I echo the **$template** it shows me include/emails/activate_account.tpl.php (which is what is mentioned in the flexi_auth config file)

But the email I receive is totally empty.

My guess it that the $this->load->view() is unable to locate the file. I have the /include/emails with all the template files in the /core/common/views but i dont think the view function is able to find these files.

**Comment by XXPerez** [comment]
@smoizs:  I think you must to try including the module in the path:

$config['email']['email_template_directory'] = 'flexi_auth/includes/email/';

// This->load>-view needs to specify module when working with HMVC.

If this not work, try to extends Flexi_auth_lite_model from Core_model:

class Flexi_auth_lite_model extends Core_Model
{
.
.
.

**Comment by smoizs** [comment]
@XMadMax awesome.. adding in the flexi_auth in the path worked! 

Thanks for your help mate.

**Comment by smoizs** [comment]
actually, I also extended the Core_Model in the Flexi_auth_lite_model.php
